Cria opção de pesquisa no Querido Diário
economiagovbr/Ro-dou pull request #14
Opened 2022-10-10 17:35 UTC by nitaibezerra

O Querido Diário é uma plataforma de coleta e indexação dos conteúdos dos Diários Oficiais de vários municípios brasileiros. Com estas mudanças é possível configurar dags para pesquisar também nos conteúdos indexados pelo Querido Diário e no DOU concomitantemente.

Além das mudanças no código fonte também foram adicionadas instruções ao README.

2022-10-22 19:03 UTC, augusto-herrmann requested changes
Excelente feature! :tada: 

Bora discutir nos comentários? Se tiver um tempinho também podemos revisar ao vivo.

2022-10-22 19:03 UTC, augusto-herrmann commented on README.md
> +Oficial da União ([DOU](https://www.gov.br/imprensanacional/pt-br)) e do Querido Diário ([QD](https://queridodiario.ok.org.br/)). Receba no email todas as publicações que contenham as
```suggestion
Oficial da União ([DOU](https://www.gov.br/imprensanacional/pt-br)) e dos Diários Oficiais de municípios por meio do Querido Diário ([QD](https://queridodiario.ok.org.br/)). Receba no email todas as publicações que contenham as
```

Acho que assim já ficaria mais claro o que a funcionalidade faz, mesmo para quem ainda não está familiarizado com o que é o Querido Diário.

2022-10-22 19:03 UTC, augusto-herrmann commented on src/dou_dag_generator.py
> +    searchers = Dict[str, BaseSearcher]
Nesta linha (e talvez na linha acima também) é o type hinting, certo?

O certo não seria assim?

```suggestion
    searchers: Dict[str, BaseSearcher]
```

2022-10-22 19:03 UTC, augusto-herrmann commented on src/dou_dag_generator.py
> +                python_callable=self.perform_searchs,
sp.

```suggestion
                python_callable=self.perform_searches,
```

2022-10-22 19:03 UTC, augusto-herrmann commented on src/dou_dag_generator.py
> +    def perform_searchs(
sp.

```suggestion
    def perform_searches(
```

2022-10-22 19:03 UTC, augusto-herrmann commented on src/report_style.css
> +    /* max-height: 44px; */
A formatação estava com problema?

2022-10-22 19:03 UTC, augusto-herrmann commented on src/searchers.py
> +        clean_text = re.sub(self.CLEAN_HTML_RE, '', raw_html)
Eu preferiria usar

```python
clean_text = BeautifulSoup(raw_html, "html.parser").get_text()
```

mas está ok.

2022-10-22 19:03 UTC, augusto-herrmann commented on src/searchers.py
> +            reference_date,
Estamos usando a `reference_date` ou a `trigger_date`? Em outros pontos do código está `trigger_date`. Agora fiquei confuso.

2022-10-24 15:23 UTC, nitaibezerra commented on src/dou_dag_generator.py
> +    searchers = Dict[str, BaseSearcher]
Exatamente, Augusto. Desatenção minha. E como o valor é sobrescrito no initializer então esse valor era descartado, causando nenhum erro que pudesse me alertar. :)

2022-10-24 15:27 UTC, nitaibezerra commented on src/report_style.css
> +    /* max-height: 44px; */
Não me recordo o motivo real. Provavelmente sim, existia um erro. Falha minha não ter separado o commit específico.

2022-10-25 11:39 UTC, nitaibezerra commented on src/searchers.py
> +        clean_text = re.sub(self.CLEAN_HTML_RE, '', raw_html)
Boa ideia. Futuramente vou mudar. Por enquanto vamos deixar assim mesmo.

2022-10-25 12:15 UTC, augusto-herrmann commented on src/searchers.py
> +            reference_date,
Combinamos de resolver as nomenclaturas em um PR futuro.

2022-10-25 12:15 UTC, merged